const data = `Ethical discussion
is based on reference points and criteria that make a dialog possible. e.g. This switch is safe (possible) vs I don't like this switch (not possible, it does not have the ground for proper discussion).

Values 
are lasting convictions or matters that people feel should be strived for in general and not just for themselves to be able to lead a good life or to realize a better society.

Absolutism
is the stricted form of universalism

Universalism 
is the ethical theory that states that there is a universally applicable system of norms and values.

Consequentialist ethics
an action is evaluated according to its consequences. You look at consequences to evaluate the “goodness” of an action. Actions are morally justifiable to the extent they promote certain values. Does a certain action promote safety, privacy, responsibility...

deontological ethics
An action is evaluated in itself. An action is morally justifiable if it follows a certain norm. Consequences don't matter

virtue ethics
An action is evaluated according to its actor An action is morally justifiable if a virtuous person does it, or would do it.

Utility principle 
is the principle that one should choose those actions that result in the greatest happiness for the greatest number.

Moral balance sheet 
is a balance sheet in which the costs and benefits (pleasures and pains) for each possible action are weighed against each other. Similar to modern cost-benefit analysis.

Freedom / no harm principle 
is the moral principle that everyone is free to strive for his/her own pleasure, as long as they do not deny or hinder the pleasure of others. One is free to do what one wishes, as long as no harm is done to others.

Marginal utility 
is the additional utility that is generated by an increase in a good or service (income for example). 100 Euro adds more happiness for a poor person, than for a rich person.

Rule utilitarianism
A variant of utilitarianism that judges actions by judging the consequences of the rules on which these actions are based. These rules, rather than the actions themselves, should maximize utility.

Duty ethics
Also known as deontological ethics. The class of approaches in ethics in which an action is considered morally right if it is in agreement with a certain moral rule (law, norm, or principle)

Good will
According to Kant, we can speak of good will if our actions are led by the moral norm. Thus, the notion of good will is different from having good intentions.

Hypothetical norm
A condition norm, that is, a norm which only applies under certain circumstances, usually of the form “If you want X do Y.”

Categorical imperative
A universal principle of the form “Do A” which is the foundation of all moral judgments in Kant’s view

Equality postulate
The prescription to treat persons as equals, that is, with equal concern and respect.

Reciprocity principle
Second formulation of the categorical imperative: Act as to treat humanity, whether in your own person or in that of any other, in every case as an end, never as means only. The reciprocity principle tells us that we should respect people as people, and not “use” them.

Universality principle
First formulation of the categorical imperative: Act only on that maxim which you can at the same time will that it should become a universal law.

Prima facie
are the applicable norms, unless they are overruled by other more important norms that become evident when we take everything into consideration.

Moral autonomy
The view that a person himself or herself should (be able to) determine what is morally right through reasoning.

Virtue ethics
An ethical theory that focuses on the nature of the acting person. This theory indicates which good or desirable characteristics people should have or develop to be moral.

Practical wisdom
The intellectual virtue that enables one to make the right choice for action. It consists in the ability to choose the right mean between two vices.

Care ethics
An ethical theory that emphasizes the importance of relationships, and which holds that the development of morals does not come about by learning general moral principles.

Social ethics
of engineering An approach to the ethics of engineering that focuses on the social arrangements in engineering rather than on individual decisions. If these social arrangements meet certain procedural norms the resulting decisions are considered acceptable

Argumentation theory
An interdisciplinary study of analyzing and evaluating arguments.

Argument 
A set of statements, of which one (the conclusion) is claimed to follow from the others (the premises).

Conclusion of an argument 
The statement that is affirmed on the basis of the premises of the argument.

Premises 
The statements, which are affirmed (or assumed) as providing support or reasons for accepting the conclusion.

Valid argument 
An argument whose conclusion follows with necessity from its premises: if the premises are true, the conclusion must be true

Modus ponens 
Form of a valid argument in which the conclusion “q” follows from the premises “p” and “if p then q.”

Fallacy 
An error or deficiency in an argument.

Modus tollens 
Form of a valid argument in which the conclusion “not-p” follows from the premises “if p then q” and “not-q.”

Deductive argument 
An argument which has a conclusion that is enclosed in (implied by) the premises. 

Plausibility principle 
The principle that enumeration and supplementary argumentation in a non-deductive argumentation can make the conclusion plausible (acceptable).

Inductive argumentation 
A type of non-deductive argumentation. Argumentation from the particular to the general. 

Critical questions 
Questions belonging to a certain type of nondeductive argumentation to check the degree of plausibility of a conclusion.

Sound argumentation 
An argumentation for which the corresponding critical questions can be answered positively and which therefore makes the conclusion plausible if the premises are true.

Argumentation by analogy
A type of non-deductive argumentation. An argumentation based on comparison with another situation in which the judgment is clear. The judgment is supposed also to apply to the analogous situation.

fallacy
false analogy / an error or deficiency in an argument

Means-end argumentation 
A type of non-deductive argumentation. An argumentation in which from a given end the means are derived to realize that end

Causality argumentation
A type of non-deductive argumentation. An argumentation in which an expected consequence is derived from certain actions.

slippery slope
wild argumentation is involved: far-reaching consequences are derived from a small cause

Proof from the absurd 
A deductive argumentation in which a certain proposition is proved by showing that the negation of the proposition leads to a contradiction.

The first categorical imperative
the universality principle

according to virtue ethics
An action is morally acceptable if and only if that action is what a virtuous agent would do in the circumstances

Characteristic-judgment argumentation 
A type of non-deductive argumentation. An argument based on the assumption that a certain judgment about a thing or person can be derived from certain characteristics of that thing or person

Ill-structured problem
A problem that has no definitive formulation of the problem, may embody inconsistent problem formulations, and can only be defined during the process of solving the problem.

Ethical cycle 
A tool in structuring and improving moral decisions by making a systematic and thorough analysis of the moral problem, which helps to come to a moral judgment and to justify the final decision in moral terms.

Moral problem 
Problem in which two or more positive moral values or norms cannot be fully realized at the same time.

Moral dilemmas 
A moral problem with the crucial feature that the agent has only two (or a limited number of ) options for action and that whatever he chooses he will commit a moral wrong

Stakeholders
Actors that have an interest (“a stake”) in the development of a technology.

Black-and-white-strategy 
A strategy for action in which only two options for actions are considered: doing the action or not.

Strategy of cooperation 
The action strategy that is directed at finding alternatives that can help to solve a moral problem by consulting other stakeholders

Intuitivist framework 
The ethical framework in which options for action are evaluated on basis of one’s view about what is intuitively most acceptable and that formulates arguments for this statement. 

Common sense method 
The method that weighs the available options for actions in the light of the relevant values.

Wide reflective equilibrium 
Approach that aims at making coherent three types of moral beliefs: 1) considered moral judgments; 2) moral principles; and 3) background theories. Also the resulting coherent set of moral beliefs is often called a wide reflective equilibrium. 

Moral deliberation 
An extensive and careful consideration or discussion of moral arguments and reasons for and against certain actions.

Overlapping consensus 
An agreement on the level of moral judgments, while there may be disagreement on the level of moral principles and background theories. Each of the participants should be able to justify the overlapping consensus in terms of his or her own wide reflective equilibrium.

Problem of many hands 
The occurrence of the situation in which the collective can reasonably be held morally responsible for an outcome, while none of the individuals can be reasonably held responsible for that outcome. 

Collective responsibility 
The responsibility of a collective of people.

Distribution of responsibility 
The ascription or apportioning of (individual) responsibilities to various actors

Moral fairness requirement 
The requirement that a distribution of responsibility should be fair (just). In case of passive responsibility, this can be interpreted as that a person should only be held responsible if that person can be reasonably held responsible according to the following conditions: wrong-doing; causal contribution; foreseeability; and freedom of action. In terms of active responsibility it can be interpreted as implying that persons should only be allocated responsibilities that they can live by

Effectiveness requirement 
The moral requirement that states that responsibility should be so distributed that the distribution has the best consequences, that is, is effective in preventing harm (and in achieving positive consequences).

Liability Legal responsibility: 
backward-looking responsibility according to the law. Usually related to the obligation to pay a fine or repair or repay damages.

Regulation 
A legal tool that can forbid the development, production, or use of certain technological products, but more often it formulates a set of the boundary conditions for the design, production, and use of technologies. 

Negligence 
Not living by certain duties. Negligence is often a main condition for legal liability. In order to show negligence for the law, usually proof must be given of a duty owed, a breach of that duty, an injury or damage, and a causal connection between the breach and the injury or damage. 

Duty of care 
The legal obligation to adhere to a reasonable standard of care when performing any acts that could foreseeably harm others. 

Strict liability 
A form of liability that does not require the defendant to be negligent.

Product liability 
Liability of manufacturers for defects in a product, without the need to proof that those manufacturers acted negligently

Development risks
In the context of product liability: Risks that could not have been foreseen given the state of scientific and technical knowledge at the time the product was put into circulation.

Corporate liability
Liability of a company (corporation) when it is treated as a legal person.

Limited liability 
The principle that the liability of shareholders for the corporation’s debts and obligations is limited to the value of their shares.

Hierarchical responsibility model 
The model in which only the organization’s top level of personnel is held responsible for the actions of (people in) the organization.

Collective responsibility model 
The model in which every member of a collective body is held responsible for the actions of the other members of that same collective body (and for the responsibility of the collective)

Individual responsibility model 
The model in which each individual is held responsible insofar as he or she meets the conditions for individual responsibility.
`;

export default data;
